name: ArenaShooter
version: '${project.version}'
main: agency.shitcoding.arena.ArenaShooter
api-version: '1.20'
author: WesOrangePower
depend: [ JellyLib, JellyGuiApi ]
softdepend: [ worldborderapi, JellyRestart ]
commands:
  arenadeathmatch:
    description: Arena Deathmatch Command
    usage: /arenadeathmatch
    aliases: [ arena ]