name: ArenaShooter
version: '${project.version}'
main: agency.shitcoding.arena.ArenaShooter
api-version: '1.21'
author: WesOrangePower
depend: [ JellyLib, JellyGuiApi, ProtocolLib ]
softdepend: [ worldborderapi, JellyRestart ]
commands:
  arena:
    description: Arena Deathmatch Command
    usage: /arena
  leave:
    description: Leave the game
    usage: /leave