package agency.shitcoding.arena;

@SuppressWarnings("unused")
public final class SoundConstants {

  public static final String ONE_FRAG = "jelly:q3.announce.1_frag";
  public static final String ONE_MINUTE = "jelly:q3.announce.1_minute";
  public static final String TWO_FRAGS = "jelly:q3.announce.2_frags";
  public static final String THREE_FRAGS = "jelly:q3.announce.3_frags";
  public static final String FIVE_MINUTE = "jelly:q3.announce.5_minute";
  public static final String ACCURACY = "jelly:q3.announce.accuracy";
  public static final String ASSIST = "jelly:q3.announce.assist";
  public static final String BASE_ATTACK = "jelly:q3.announce.base_attack";
  public static final String BLUELEADS = "jelly:q3.announce.blueleads";
  public static final String BLUE_RETURNED = "jelly:q3.announce.blue_returned";
  public static final String BLUE_SCORES = "jelly:q3.announce.blue_scores";
  public static final String CAPTURES = "jelly:q3.announce.captures";
  public static final String DEFENSE = "jelly:q3.announce.defense";
  public static final String DENIED = "jelly:q3.announce.denied";
  public static final String ENEMY_1FLAG = "jelly:q3.announce.enemy_1flag";
  public static final String ENEMY_FLAG = "jelly:q3.announce.enemy_flag";
  public static final String EXCELLENT = "jelly:q3.announce.excellent";
  public static final String EXCELLENT_A = "jelly:q3.announce.excellent_a";
  public static final String FIGHT = "jelly:q3.announce.fight";
  public static final String FIRST_EXCELLENT = "jelly:q3.announce.first_excellent";
  public static final String FIRST_GAUNTLET = "jelly:q3.announce.first_gauntlet";
  public static final String FIRST_IMPRESSIVE = "jelly:q3.announce.first_impressive";
  public static final String FRAGS = "jelly:q3.announce.frags";
  public static final String GAUNTLET = "jelly:q3.announce.gauntlet";
  public static final String HOLYSHIT = "jelly:q3.announce.holyshit";
  public static final String HUMILIATION = "jelly:q3.announce.humiliation";
  public static final String IMPRESSIVE = "jelly:q3.announce.impressive";
  public static final String INTRO_01 = "jelly:q3.announce.intro_01";
  public static final String INTRO_02 = "jelly:q3.announce.intro_02";
  public static final String INTRO_04 = "jelly:q3.announce.intro_04";
  public static final String INTRO_09 = "jelly:q3.announce.intro_09";
  public static final String INTRO_10 = "jelly:q3.announce.intro_10";
  public static final String INTRO_11 = "jelly:q3.announce.intro_11";
  public static final String LOSTLEAD = "jelly:q3.announce.lostlead";
  public static final String MENU_ACCURACY = "jelly:q3.announce.menu_accuracy";
  public static final String MENU_ASSIST = "jelly:q3.announce.menu_assist";
  public static final String MENU_CAPTURES = "jelly:q3.announce.menu_captures";
  public static final String MENU_DEFENSE = "jelly:q3.announce.menu_defense";
  public static final String MENU_EXCELLENT = "jelly:q3.announce.menu_excellent";
  public static final String MENU_GAUNTLET = "jelly:q3.announce.menu_gauntlet";
  public static final String MENU_IMPRESSIVE = "jelly:q3.announce.menu_impressive";
  public static final String NEW_HIGH_SCORE = "jelly:q3.announce.new_high_score";
  public static final String ONE = "jelly:q3.announce.one";
  public static final String PERFECT = "jelly:q3.announce.perfect";
  public static final String PREPARE = "jelly:q3.announce.prepare";
  public static final String PREPARE_TEAM = "jelly:q3.announce.prepare_team";
  public static final String RED_LEADS = "jelly:q3.announce.red_leads";
  public static final String RED_RETURNED = "jelly:q3.announce.red_returned";
  public static final String RED_SCORES = "jelly:q3.announce.red_scores";
  public static final String REGENERATION = "jelly:q3.announce.regeneration";
  public static final String SUDDEN_DEATH = "jelly:q3.announce.sudden_death";
  public static final String TAKEN_LEAD = "jelly:q3.announce.taken_lead";
  public static final String TEAMS_TIED = "jelly:q3.announce.teams_tied";
  public static final String TEAM_1FLAG = "jelly:q3.announce.team_1flag";
  public static final String TEAM_FLAG = "jelly:q3.announce.team_flag";
  public static final String THREE = "jelly:q3.announce.three";
  public static final String TIED_LEAD = "jelly:q3.announce.tied_lead";
  public static final String TWO = "jelly:q3.announce.two";
  public static final String VOTE_FAILED = "jelly:q3.announce.vote_failed";
  public static final String VOTE_NOW = "jelly:q3.announce.vote_now";
  public static final String VOTE_PASSED = "jelly:q3.announce.vote_passed";
  public static final String YOU_FLAG = "jelly:q3.announce.you_flag";
  public static final String YOU_LOSE = "jelly:q3.announce.you_lose";
  public static final String YOU_WIN = "jelly:q3.announce.you_win";
  public static final String AMMO_PICKUP = "jelly:q3.weapon.am_pick";
  public static final String BUFF_PICKUP = "jelly:q3.weapon.bu_pick";
  public static final String WEAPON_PICKUP = "jelly:q3.weapon.we_pick";
  public static final String MAJOR_BUFF_PICKUP = "jelly:q3.weapon.protect";
  public static final String HITSOUND = "jelly:q3.weapon.hit";
  public static final String NOAMMO = "jelly:q3.weapon.noammo";
  public static final String MACHINE_FIRE = "jelly:q3.weapon.machine_fire";
  public static final String RAIL_FIRE = "jelly:q3.weapon.rail_fire";
  public static final String ROCKET_FIRE = "jelly:q3.weapon.rocket_fire";
  public static final String ROCKET_DET = "jelly:q3.weapon.rocket_det";
  public static final String SSG_FIRE = "jelly:q3.weapon.ssg_fire";
  public static final String PLASMA_FIRE = "jelly:q3.weapon.plasma_fire";
  public static final String PLASMA_HIT = "jelly:q3.weapon.plasma_hit";
  public static final String LG_FIRE = "jelly:q3.weapon.lg_fire";
  public static final String BFG_FIRE = "jelly:q3.weapon.bfg_fire";
  public static final String BFG_HIT = "jelly:q3.weapon.bfg_hit";
  public static final String PAD = "jelly:q3.misc.pad";

    private SoundConstants() {
    }
}
