name: Build & Deploy

on:
  push:
    branches: 
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
        server-id: nexus-jelly
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
    - name: Rename jar to ArenaShooter.jar
      run: mv server/plugins/*.jar server/plugins/ArenaShooter.jar
    - name: DEBUG
      run: ls server/plugins
    - name: DEBUG 2
      run: ls target
    - name: Upload jar
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        source: "server/plugins/ArenaShooter.jar"
        target: "/var/jelly/Arena/plugins"
    - name: Restart server
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        key: ${{ secrets.KEY }}
        port: ${{ secrets.PORT }}
        script: docker exec -t Arena sh -c "cd /dist && ./run_command \"JellyRestart:restart start 60\""
    - name: Publish with maven
      run: mvn -B deploy --file pom.xml
      env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
