name: Release
on:
  release:
    types: [created]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
      - if: github.event.release
        name: Update version in pom.xml (if release)
        run: >
          mvn -B versions:set 
          -DnewVersion=${{ github.event.release.tag_name }} 
          -DgenerateBackupPoms=false
      - name: Publish with maven
        run: mvn -B deploy --file pom.xml
        env:
          MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          path: server/target/ArenaShooter*.jar
          name: 'ArenaShooter'
